In [2]:
# Exercise 1
import numpy as np
a = np.array([8, 12, 16, 24, 4])
mean = np.mean(a)
summ = round(np.sum(a - mean), 2)
print("%.2f" % np.std(a), mean, summ)

6.88 12.8 -0.0


In [11]:
# Exercise 2
import numpy as np
a = [8, 12, 16, 24, 4]
b = [8, 12, 16, 78, 24, 4, 300]
an = np.array(a)
bn = np.array(b)
print("%.2f" % np.std(an), "%.2f" % np.std(bn), sep='\n')

#If outliers are introduced to the dataset the Standart Deviation will increase

6.88
99.45


In [ ]:
# Exercise 3
# Suppose the below positively skewed distribution has a median of 30, which of the following statement is true?
# Statement E) Both A and D (Mean is greater than 30, Mode is less than 30) is true.

6.88
99.45


In [14]:
# Exercise 4
# [9, 12, 17, 20, 13, 10, 6, 5, 3]
# sorted [3, 5, 6, 9, 10, 12, 13, 17, 20]
# count = 9 - odd number
# median = 10

In [ ]:
# Exercise 5 - 7
# The shape is Skewed Right
# [1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 5, 6, 9, 11, 24, 29]
# count = 16
# median = (3 + 3) / 2 = 3
# mean = 105 / 16 = 6.5
# individuals that have salary less than 10k, n = 35

In [75]:
# Exercise 8
def mode(np_array):
    bin_count = np.bincount(np_array)
    maximum = bin_count.max()
    maxs = []
    for i in range(len(bin_count)):
        if bin_count[i] == maximum:
            maxs.append(i)
    return maxs

a = np.array([1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 5, 6, 9, 11, 24, 29])
b = np.array([1, 1, 7, 1, 2, 2, 3, 3, 3, 4, 5, 6, 9, 11, 24, 29])

print(np.mean(a), np.median(a), mode(a))
print(np.mean(b), np.median(b), mode(b))

# Answer is D) All of these (The Mean, the Median and the Mode can change if a single value would be changed)

6.5625 3.0 [1]
6.625 3.0 [1, 3]


In [78]:
# Exercise 9
s = np.array([[3, 2, 1, 4], [25, 40, 35, 50]])
salaries = []
print(s[0, 1])
for i in range(len(s[0])):
    for j in range(s[0, i]):
        salaries.append(s[1, i])
print(salaries)
print("%.2f" % np.std(salaries))

2
[25, 25, 25, 40, 40, 35, 50, 50, 50, 50]
10.44


In [ ]:
# Exercise 10
# Which of the following random variables is discrete?
# B) the number of pens purchased by a student in a year

In [ ]:
# Exercise 11
# B) mu=10, sigma =1.0

In [ ]:
#### 100 Numpy Exercises

#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [ ]:
#### 2. Print the numpy version and the configuration (★☆☆)
print("#2\n", np.version.version)

In [ ]:
#### 3. Create a null vector of size 10 (★☆☆)
vec = np.zeros(10)
print("#3\n", vec)

In [ ]:
#### 4. How to find the memory size of any array (★☆☆)
print("#4\n", vec.size)

In [ ]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
# print(np.info(np.add))

In [ ]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
vec[4] = 1
print("#6\n", vec)


In [ ]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
ar_range = np.arange(10, 50)
print("#7\n", ar_range)


In [ ]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
print("#8\n", np.flip(ar_range))

In [ ]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrx = np.arange(9).reshape((3, 3))
print("#9\n", matrx)


In [ ]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
arr = np.array([1, 2, 0, 0, 4, 0])
print("#10\n", np.where(arr != 0)[0])


In [ ]:
#### 11. Create a 3x3 identity matrix (★☆☆)
print("#11\n",np.identity(3))

In [ ]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
print("#12\n",np.random.randint(1, 10, (3, 3, 3)))

In [ ]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
rand_arr = np.random.randint(1, 100, (10, 10))
print("#13\n",rand_arr)
print("Max is ", np.max(rand_arr))
print("Min is ", np.min(rand_arr))


In [ ]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
r_vec = np.random.randint(1, 100, (30))
print("#14\n", r_vec)
print("%.2f" % np.mean(r_vec))

In [ ]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
arr_1 = np.zeros((5, 5))
# arr_1[0, :] = 1
# arr_1[:, 0] = 1
# arr_1[-1, :] = 1
# arr_1[:, -1] = 1
b_arr = np.pad(arr_1, pad_width=1, mode='constant', constant_values = 1)
print("#15\n", b_arr)

In [ ]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
arr_1 = np.ones((3, 3))
b_arr = np.pad(arr_1, pad_width=1, mode='constant', constant_values = 0)
print("#16\n", b_arr)


In [ ]:
#### 17. What is the result of the following expression? (★☆☆)
print("#17\n", 0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

In [ ]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
a = np.zeros((5, 5))
d = np.array([1, 2, 3, 4])
np.fill_diagonal(a, d, wrap=True)
print("#18\n", a)


In [ ]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
a = np.zeros((8,8))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print("#19\n", a)

In [ ]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
print("#20\n", np.unravel_index(99,(6,7,8)))

In [ ]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
a = np.array([[0, 1], [1, 0]])
b = np.tile(a, (4, 4))
print("#21\n", b)

In [ ]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
import math
a = np.random.randint(0, 20, (5, 5))
n_a = a / np.linalg.norm(a)
print("#22\n", n_a)
print(a / math.sqrt(np.sum(a ** 2)))

In [ ]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
dtype_rgba = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
colors = np.array([[255, 0, 0, 255], [255, 0, 0, 255], [255, 0, 0, 255], [255, 0, 0, 255]], dtype=np.uint8)
print("#23\n", colors, "\n", dtype_rgba.names)


In [ ]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
a = np.random.randint(0, 10, (5, 3))
b = np.random.randint(0, 10, (3, 2))
print("#24\n", np.matmul(a, b))


In [ ]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
a = np.random.randint(1, 20, (10))
a[(a > 3) & (a < 8)] *= -1
print("#25\n", a)

In [ ]:
#### 26. What is the output of the following script? (★☆☆)
# print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))


In [ ]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z = np.random.randint(1, 10, (10))
# print(Z**Z)
# print(2 << Z >> 2)
# print(Z <- Z)
# print(1j*Z)
# print(Z/1/1)
# print(Z<Z>Z)

In [ ]:
#### 28. What are the result of the following expressions? (★☆☆)
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

In [ ]:
#### 29. How to round away from zero a float array ? (★☆☆)

# SKIPPED

In [ ]:
#### 30. How to find common values between two arrays? (★☆☆)
a = np.random.randint(1, 10, (10))
b = np.random.randint(1, 10, (10))
print("#30\n", a, "\n", b)
print(np.intersect1d(a, b))

In [138]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
# np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [5]:
#### 32. Is the following expressions true? (★☆☆)
print(np.sqrt(-1) == np.emath.sqrt(-1))


1j


In [23]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2023-08-02 2023-08-03 2023-08-04


In [30]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
dates = np.arange(np.datetime64("2016-07-01"), np.datetime64("2016-08-01"), np.timedelta64(1, "D"))
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [41]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
A = np.ones(3)
B = np.ones(3)*2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(A)

[-1.5 -1.5 -1.5]


In [54]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
a = np.random.uniform(1, 10, (10))
print(a)
print(a.astype(int))
print(np.modf(a)[1])
print(np.floor(a))
print(a // 1)
print(a - a%1)

[4.46099971 2.79682291 8.84368268 6.05596146 1.56392679 8.26703914
 3.69557319 5.85112025 1.28352027 1.36601964]
[4 2 8 6 1 8 3 5 1 1]
[4. 2. 8. 6. 1. 8. 3. 5. 1. 1.]
[4. 2. 8. 6. 1. 8. 3. 5. 1. 1.]
[4. 2. 8. 6. 1. 8. 3. 5. 1. 1.]
[4. 2. 8. 6. 1. 8. 3. 5. 1. 1.]


In [68]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
a = np.mgrid[0:5, 0:5][1]
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [91]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
import random

def int_gen(n):
    for i in range(n):
        yield random.randint(1, 10)

a = np.fromiter(int_gen(10), int)
print(a)

[ 3  1  4  5 10  1  9  4  8  3]


In [95]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
a = np.linspace(0, 1, 10, endpoint=False)[1:]
print(a)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [98]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
a = np.random.random(10)
print(np.sort(a))

[0.06966401 0.20458523 0.21284585 0.5081308  0.53986481 0.55498317
 0.58868033 0.76549603 0.89629203 0.99323261]


In [ ]:
#### 41. How to sum a small array faster than np.sum? (★★☆)

# SKIPPED

In [6]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)
a = np.array([[1, 2, 5, 5 ,5, 8], [2, 3, 4, 1, 0, 9]])
b = np.array([[1, 2, 5, 5 ,5, 8], [2, 3, 4, 1, 0, 9]])
print(np.array_equal(a, b))

True


In [9]:
#### 43. Make an array immutable (read-only) (★★☆)
a = np.array([[1, 2, 5, 5 ,5, 8], [2, 3, 4, 1, 0, 9]])
a.flags.writeable = False

In [27]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
c = np.random.randint(1, 10, (10, 2))
print(c)
p = np.transpose(np.vstack((np.sqrt(c[:, 0]**2 + c[:, 1]**2), np.arctan2(c[:, 1], c[:, 0]))))
print(p)

[[5 9]
 [8 4]
 [5 4]
 [4 1]
 [8 5]
 [3 5]
 [1 8]
 [4 4]
 [5 1]
 [4 9]]
[[10.29563014  1.06369782]
 [ 8.94427191  0.46364761]
 [ 6.40312424  0.67474094]
 [ 4.12310563  0.24497866]
 [ 9.43398113  0.55859932]
 [ 5.83095189  1.03037683]
 [ 8.06225775  1.44644133]
 [ 5.65685425  0.78539816]
 [ 5.09901951  0.19739556]
 [ 9.8488578   1.152572  ]]


In [41]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
a = np.random.randint(0, 10, (10))
print(a)
a[np.where(a == a.max())[0]] = 0
print(a)


[4 8 3 7 8 2 0 7 7 5]
[4 0 3 7 0 2 0 7 7 5]
